### ISSUE TITLE
DialogApi error 

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/skill_TextInputWidget#4]
Not a biggy but if using text input widget and the intent is not ended properly the sessionId remains in the SessionID box. Clicking the "send button" during this occasion puts the follwoing error in the logs
 
```[13:23:56.500] [DialogApi]Failed processing: 'NoneType' object has no attribute 'sessionId'```

**Comment by LazzaAU** [comment]
Im not a JS person so not cant help much more with this other than for me ...

by using text input of "whats the time" and getting the correct answer
 
simpleCommands.js lines 135 always goes into the "return" and even if it was able to get to line 140,.... for me ```msg.destinationName``` 
is never
 ``` hermes/dialogueManager/sessionEnded```
 and is always
 ```hermes/nlu/intentParsed```
 and  a following 
```hermes/tts/say``` ?

Hope that helps save some time when you get to it

**Comment by philipp2310** [comment]
SimpleInput is currently disabled as it is replaced by DialogView
